SELECT * FROM retail_customers;

-- Answer some Business Questions

-- Q1. What is the total revenue generated by male vs. female customers?
-- Q2. Which customers used a discount but still spent more than the average purachase amount?
-- Q3. Which are the top 5 products with the highest average review rating?
-- Q4. Compare the average Purchase Amounrs netween Standard and Express Shipping.
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- Q7. Segment customers into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segment.
-- Q8. What are the top 3 most purchased products within each category?
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Q10. What is the revenue contributio of each age group?
-- Q11. Find Top 5 Purchases and their Revenue of Each age group


-- Q1. What is the total revenue generated by male vs. female customers?

SELECT * FROM retail_customers LIMIT 5;

SELECT gender, SUM(purchase_amount) as Revenue
FROM retail_customers
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purachase amount?

SELECT * FROM retail_customers LIMIT 5;

SELECT *
FROM retail_customers
WHERE discount_applied = 'Yes' and purchase_amount >(SELECT ROUND(AVG(purchase_amount),2) AS avg_purchased_amount 
													  FROM retail_customers);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT * FROM retail_customers LIMIT 5;

SELECT 
	item_purchased,
	ROUND(AVG(review_rating)::numeric,2) AS avg_rating
FROM retail_customers
GROUP BY item_purchased 
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT * FROM retail_customers LIMIT 5;

SELECT shipping_type, ROUND(AVG(purchase_amount) ,2) AS avg_revenue
FROM retail_customers
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT * FROM retail_customers LIMIT 5;

SELECT subscription_status, COUNT(*)AS total_customer, ROUND(AVG(purchase_amount),2) AS avg_spend, SUM(purchase_amount) AS total_revenue
FROM retail_customers
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT * FROM retail_customers LIMIT 5;

SELECT 
	item_purchased AS product,
	COUNT(*) AS no_of_product,
	SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discount_purchases,
	ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)::numeric,2) as discount_percentage
FROM retail_customers
GROUP BY item_purchased
ORDER BY discount_percentage
limit 5;


-- Q7. Segment customers into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segment.

SELECT * FROM retail_customers LIMIT 5;

WITH segment_cte AS(
	SELECT customer_id, previous_purchases,
		CASE 
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
		END AS customer_segment
	FROM retail_customers
)
SELECT customer_segment, COUNT(*) no_of_customer
FROM segment_cte
GROUP BY customer_segment
ORDER BY no_of_customer DESC;


-- Q8. What are the top 3 most purchased products within each category?

SELECT * FROM retail_customers LIMIT 5;


WITH CTE AS(
	SELECT 
		category,
		item_purchased,
		SUM(purchase_amount) as revenue
	FROM retail_customers
	GROUP BY category,item_purchased
),
ranked_cte AS(
	SELECT
		category,
		item_purchased,
		revenue,
		DENSE_RANK() OVER(PARTITION BY category ORDER BY revenue DESC) ranked
	FROM CTE
)
SELECT 
	category,
	item_purchased,
	revenue
FROM ranked_cte
WHERE ranked <= 3

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT * FROM retail_customers LIMIT 5;

SELECT subscription_status, COUNT(*) AS total_buyers
FROM retail_customers
WHERE previous_purchases >= 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?

SELECT * FROM retail_customers LIMIT 5;

SELECT age_group, SUM(purchase_amount) AS revenue
FROM retail_customers
GROUP BY age_group
ORDER BY revenue DESC;

-- Q11. Top 5 Purchases and their revenue by each Age_group

SELECT * FROM retail_customers LIMIT 5;

WITH CTE AS(
	SELECT 
		age_group,
		item_purchased,
		COUNT(*) AS item_count,
		SUM(purchase_amount) as revenue
	FROM retail_customers
	GROUP BY age_group, item_purchased
),
counted_rnked AS(
	SELECT 
		age_group,
		item_purchased,
		item_count,
		revenue,
		DENSE_RANK() OVER(PARTITION BY age_group ORDER BY item_count DESC) AS counted_rnk
	FROM CTE
)
SELECT 
	age_group,
	item_purchased,
	item_count,
	revenue
FROM counted_rnked
WHERE counted_rnk <=5;


